/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.commands;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Ships command feedback through MQ. */
@org.apache.avro.specific.AvroGenerated
public class BareResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3508694899211238573L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BareResponse\",\"namespace\":\"avro.commands\",\"doc\":\"Ships command feedback through MQ.\",\"fields\":[{\"name\":\"succeeded\",\"type\":\"boolean\"},{\"name\":\"feedback\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BareResponse> ENCODER =
      new BinaryMessageEncoder<BareResponse>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BareResponse> DECODER =
      new BinaryMessageDecoder<BareResponse>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BareResponse> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BareResponse> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BareResponse>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BareResponse to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BareResponse from a ByteBuffer. */
  public static BareResponse fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public boolean succeeded;
  @Deprecated public java.lang.String feedback;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BareResponse() {}

  /**
   * All-args constructor.
   * @param succeeded The new value for succeeded
   * @param feedback The new value for feedback
   */
  public BareResponse(java.lang.Boolean succeeded, java.lang.String feedback) {
    this.succeeded = succeeded;
    this.feedback = feedback;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return succeeded;
    case 1: return feedback;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: succeeded = (java.lang.Boolean)value$; break;
    case 1: feedback = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'succeeded' field.
   * @return The value of the 'succeeded' field.
   */
  public java.lang.Boolean getSucceeded() {
    return succeeded;
  }

  /**
   * Sets the value of the 'succeeded' field.
   * @param value the value to set.
   */
  public void setSucceeded(java.lang.Boolean value) {
    this.succeeded = value;
  }

  /**
   * Gets the value of the 'feedback' field.
   * @return The value of the 'feedback' field.
   */
  public java.lang.String getFeedback() {
    return feedback;
  }

  /**
   * Sets the value of the 'feedback' field.
   * @param value the value to set.
   */
  public void setFeedback(java.lang.String value) {
    this.feedback = value;
  }

  /**
   * Creates a new BareResponse RecordBuilder.
   * @return A new BareResponse RecordBuilder
   */
  public static avro.commands.BareResponse.Builder newBuilder() {
    return new avro.commands.BareResponse.Builder();
  }

  /**
   * Creates a new BareResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BareResponse RecordBuilder
   */
  public static avro.commands.BareResponse.Builder newBuilder(avro.commands.BareResponse.Builder other) {
    return new avro.commands.BareResponse.Builder(other);
  }

  /**
   * Creates a new BareResponse RecordBuilder by copying an existing BareResponse instance.
   * @param other The existing instance to copy.
   * @return A new BareResponse RecordBuilder
   */
  public static avro.commands.BareResponse.Builder newBuilder(avro.commands.BareResponse other) {
    return new avro.commands.BareResponse.Builder(other);
  }

  /**
   * RecordBuilder for BareResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BareResponse>
    implements org.apache.avro.data.RecordBuilder<BareResponse> {

    private boolean succeeded;
    private java.lang.String feedback;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.commands.BareResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.succeeded)) {
        this.succeeded = data().deepCopy(fields()[0].schema(), other.succeeded);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.feedback)) {
        this.feedback = data().deepCopy(fields()[1].schema(), other.feedback);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BareResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.commands.BareResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.succeeded)) {
        this.succeeded = data().deepCopy(fields()[0].schema(), other.succeeded);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.feedback)) {
        this.feedback = data().deepCopy(fields()[1].schema(), other.feedback);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'succeeded' field.
      * @return The value.
      */
    public java.lang.Boolean getSucceeded() {
      return succeeded;
    }

    /**
      * Sets the value of the 'succeeded' field.
      * @param value The value of 'succeeded'.
      * @return This builder.
      */
    public avro.commands.BareResponse.Builder setSucceeded(boolean value) {
      validate(fields()[0], value);
      this.succeeded = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'succeeded' field has been set.
      * @return True if the 'succeeded' field has been set, false otherwise.
      */
    public boolean hasSucceeded() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'succeeded' field.
      * @return This builder.
      */
    public avro.commands.BareResponse.Builder clearSucceeded() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'feedback' field.
      * @return The value.
      */
    public java.lang.String getFeedback() {
      return feedback;
    }

    /**
      * Sets the value of the 'feedback' field.
      * @param value The value of 'feedback'.
      * @return This builder.
      */
    public avro.commands.BareResponse.Builder setFeedback(java.lang.String value) {
      validate(fields()[1], value);
      this.feedback = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'feedback' field has been set.
      * @return True if the 'feedback' field has been set, false otherwise.
      */
    public boolean hasFeedback() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'feedback' field.
      * @return This builder.
      */
    public avro.commands.BareResponse.Builder clearFeedback() {
      feedback = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BareResponse build() {
      try {
        BareResponse record = new BareResponse();
        record.succeeded = fieldSetFlags()[0] ? this.succeeded : (java.lang.Boolean) defaultValue(fields()[0]);
        record.feedback = fieldSetFlags()[1] ? this.feedback : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BareResponse>
    WRITER$ = (org.apache.avro.io.DatumWriter<BareResponse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BareResponse>
    READER$ = (org.apache.avro.io.DatumReader<BareResponse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
