/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.commands;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CreateFileCommand extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -560756587307310977L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CreateFileCommand\",\"namespace\":\"avro.commands\",\"fields\":[{\"name\":\"file\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"content\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CreateFileCommand> ENCODER =
      new BinaryMessageEncoder<CreateFileCommand>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CreateFileCommand> DECODER =
      new BinaryMessageDecoder<CreateFileCommand>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<CreateFileCommand> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<CreateFileCommand> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CreateFileCommand>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this CreateFileCommand to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a CreateFileCommand from a ByteBuffer. */
  public static CreateFileCommand fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String file;
  @Deprecated public java.lang.String content;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CreateFileCommand() {}

  /**
   * All-args constructor.
   * @param file The new value for file
   * @param content The new value for content
   */
  public CreateFileCommand(java.lang.String file, java.lang.String content) {
    this.file = file;
    this.content = content;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return file;
    case 1: return content;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: file = (java.lang.String)value$; break;
    case 1: content = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'file' field.
   * @return The value of the 'file' field.
   */
  public java.lang.String getFile() {
    return file;
  }

  /**
   * Sets the value of the 'file' field.
   * @param value the value to set.
   */
  public void setFile(java.lang.String value) {
    this.file = value;
  }

  /**
   * Gets the value of the 'content' field.
   * @return The value of the 'content' field.
   */
  public java.lang.String getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.String value) {
    this.content = value;
  }

  /**
   * Creates a new CreateFileCommand RecordBuilder.
   * @return A new CreateFileCommand RecordBuilder
   */
  public static avro.commands.CreateFileCommand.Builder newBuilder() {
    return new avro.commands.CreateFileCommand.Builder();
  }

  /**
   * Creates a new CreateFileCommand RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CreateFileCommand RecordBuilder
   */
  public static avro.commands.CreateFileCommand.Builder newBuilder(avro.commands.CreateFileCommand.Builder other) {
    return new avro.commands.CreateFileCommand.Builder(other);
  }

  /**
   * Creates a new CreateFileCommand RecordBuilder by copying an existing CreateFileCommand instance.
   * @param other The existing instance to copy.
   * @return A new CreateFileCommand RecordBuilder
   */
  public static avro.commands.CreateFileCommand.Builder newBuilder(avro.commands.CreateFileCommand other) {
    return new avro.commands.CreateFileCommand.Builder(other);
  }

  /**
   * RecordBuilder for CreateFileCommand instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CreateFileCommand>
    implements org.apache.avro.data.RecordBuilder<CreateFileCommand> {

    private java.lang.String file;
    private java.lang.String content;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.commands.CreateFileCommand.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.file)) {
        this.file = data().deepCopy(fields()[0].schema(), other.file);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing CreateFileCommand instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.commands.CreateFileCommand other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.file)) {
        this.file = data().deepCopy(fields()[0].schema(), other.file);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'file' field.
      * @return The value.
      */
    public java.lang.String getFile() {
      return file;
    }

    /**
      * Sets the value of the 'file' field.
      * @param value The value of 'file'.
      * @return This builder.
      */
    public avro.commands.CreateFileCommand.Builder setFile(java.lang.String value) {
      validate(fields()[0], value);
      this.file = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'file' field has been set.
      * @return True if the 'file' field has been set, false otherwise.
      */
    public boolean hasFile() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'file' field.
      * @return This builder.
      */
    public avro.commands.CreateFileCommand.Builder clearFile() {
      file = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'content' field.
      * @return The value.
      */
    public java.lang.String getContent() {
      return content;
    }

    /**
      * Sets the value of the 'content' field.
      * @param value The value of 'content'.
      * @return This builder.
      */
    public avro.commands.CreateFileCommand.Builder setContent(java.lang.String value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'content' field has been set.
      * @return True if the 'content' field has been set, false otherwise.
      */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'content' field.
      * @return This builder.
      */
    public avro.commands.CreateFileCommand.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CreateFileCommand build() {
      try {
        CreateFileCommand record = new CreateFileCommand();
        record.file = fieldSetFlags()[0] ? this.file : (java.lang.String) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CreateFileCommand>
    WRITER$ = (org.apache.avro.io.DatumWriter<CreateFileCommand>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CreateFileCommand>
    READER$ = (org.apache.avro.io.DatumReader<CreateFileCommand>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
