/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.commands;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Curse extends org.apache.avro.specific.SpecificExceptionBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3502353900602985612L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"error\",\"name\":\"Curse\",\"namespace\":\"avro.commands\",\"fields\":[{\"name\":\"message\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();


  @Deprecated public java.lang.CharSequence message$;

  public Curse() {
    super();
  }

  public Curse(Object value) {
    super(value);
  }

  public Curse(Throwable cause) {
    super(cause);
  }

  public Curse(Object value, Throwable cause) {
    super(value, cause);
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return message$;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: message$ = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'message$' field.
   * @return The value of the 'message$' field.
   */
  public java.lang.CharSequence getMessage$() {
    return message$;
  }

  /**
   * Sets the value of the 'message$' field.
   * @param value the value to set.
   */
  public void setMessage$(java.lang.CharSequence value) {
    this.message$ = value;
  }

  /**
   * Creates a new Curse RecordBuilder.
   * @return A new Curse RecordBuilder
   */
  public static avro.commands.Curse.Builder newBuilder() {
    return new avro.commands.Curse.Builder();
  }

  /**
   * Creates a new Curse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Curse RecordBuilder
   */
  public static avro.commands.Curse.Builder newBuilder(avro.commands.Curse.Builder other) {
    return new avro.commands.Curse.Builder(other);
  }

  /**
   * Creates a new Curse RecordBuilder by copying an existing Curse instance.
   * @param other The existing instance to copy.
   * @return A new Curse RecordBuilder
   */
  public static avro.commands.Curse.Builder newBuilder(avro.commands.Curse other) {
    return new avro.commands.Curse.Builder(other);
  }

  /**
   * RecordBuilder for Curse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificErrorBuilderBase<Curse>
    implements org.apache.avro.data.ErrorBuilder<Curse> {

    private java.lang.CharSequence message$;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.commands.Curse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Curse instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.commands.Curse other) {
      super(other);
      if (isValidValue(fields()[0], other.message$)) {
        this.message$ = data().deepCopy(fields()[0].schema(), other.message$);
        fieldSetFlags()[0] = true;
      }
    }

    @Override
    public avro.commands.Curse.Builder setValue(Object value) {
      super.setValue(value);
      return this;
    }

    @Override
    public avro.commands.Curse.Builder clearValue() {
      super.clearValue();
      return this;
    }

    @Override
    public avro.commands.Curse.Builder setCause(Throwable cause) {
      super.setCause(cause);
      return this;
    }

    @Override
    public avro.commands.Curse.Builder clearCause() {
      super.clearCause();
      return this;
    }

    /**
      * Gets the value of the 'message$' field.
      * @return The value.
      */
    public java.lang.CharSequence getMessage$() {
      return message$;
    }

    /**
      * Sets the value of the 'message$' field.
      * @param value The value of 'message$'.
      * @return This builder.
      */
    public avro.commands.Curse.Builder setMessage$(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.message$ = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'message$' field has been set.
      * @return True if the 'message$' field has been set, false otherwise.
      */
    public boolean hasMessage$() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'message$' field.
      * @return This builder.
      */
    public avro.commands.Curse.Builder clearMessage$() {
      message$ = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Curse build() {
      try {
        Curse record = new Curse(getValue(), getCause());
        record.message$ = fieldSetFlags()[0] ? this.message$ : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Curse>
    WRITER$ = (org.apache.avro.io.DatumWriter<Curse>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Curse>
    READER$ = (org.apache.avro.io.DatumReader<Curse>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
