/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.commands;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RemoveDirCommand extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4740564011197644794L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RemoveDirCommand\",\"namespace\":\"avro.commands\",\"fields\":[{\"name\":\"path\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RemoveDirCommand> ENCODER =
      new BinaryMessageEncoder<RemoveDirCommand>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RemoveDirCommand> DECODER =
      new BinaryMessageDecoder<RemoveDirCommand>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RemoveDirCommand> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RemoveDirCommand> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RemoveDirCommand>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RemoveDirCommand to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RemoveDirCommand from a ByteBuffer. */
  public static RemoveDirCommand fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence path;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RemoveDirCommand() {}

  /**
   * All-args constructor.
   * @param path The new value for path
   */
  public RemoveDirCommand(java.lang.CharSequence path) {
    this.path = path;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return path;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: path = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'path' field.
   * @return The value of the 'path' field.
   */
  public java.lang.CharSequence getPath() {
    return path;
  }

  /**
   * Sets the value of the 'path' field.
   * @param value the value to set.
   */
  public void setPath(java.lang.CharSequence value) {
    this.path = value;
  }

  /**
   * Creates a new RemoveDirCommand RecordBuilder.
   * @return A new RemoveDirCommand RecordBuilder
   */
  public static avro.commands.RemoveDirCommand.Builder newBuilder() {
    return new avro.commands.RemoveDirCommand.Builder();
  }

  /**
   * Creates a new RemoveDirCommand RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RemoveDirCommand RecordBuilder
   */
  public static avro.commands.RemoveDirCommand.Builder newBuilder(avro.commands.RemoveDirCommand.Builder other) {
    return new avro.commands.RemoveDirCommand.Builder(other);
  }

  /**
   * Creates a new RemoveDirCommand RecordBuilder by copying an existing RemoveDirCommand instance.
   * @param other The existing instance to copy.
   * @return A new RemoveDirCommand RecordBuilder
   */
  public static avro.commands.RemoveDirCommand.Builder newBuilder(avro.commands.RemoveDirCommand other) {
    return new avro.commands.RemoveDirCommand.Builder(other);
  }

  /**
   * RecordBuilder for RemoveDirCommand instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RemoveDirCommand>
    implements org.apache.avro.data.RecordBuilder<RemoveDirCommand> {

    private java.lang.CharSequence path;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.commands.RemoveDirCommand.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RemoveDirCommand instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.commands.RemoveDirCommand other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.path)) {
        this.path = data().deepCopy(fields()[0].schema(), other.path);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'path' field.
      * @return The value.
      */
    public java.lang.CharSequence getPath() {
      return path;
    }

    /**
      * Sets the value of the 'path' field.
      * @param value The value of 'path'.
      * @return This builder.
      */
    public avro.commands.RemoveDirCommand.Builder setPath(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.path = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'path' field has been set.
      * @return True if the 'path' field has been set, false otherwise.
      */
    public boolean hasPath() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'path' field.
      * @return This builder.
      */
    public avro.commands.RemoveDirCommand.Builder clearPath() {
      path = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RemoveDirCommand build() {
      try {
        RemoveDirCommand record = new RemoveDirCommand();
        record.path = fieldSetFlags()[0] ? this.path : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RemoveDirCommand>
    WRITER$ = (org.apache.avro.io.DatumWriter<RemoveDirCommand>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RemoveDirCommand>
    READER$ = (org.apache.avro.io.DatumReader<RemoveDirCommand>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
