/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package avro.commands;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RenameDirCommand extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4160062809255016306L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RenameDirCommand\",\"namespace\":\"avro.commands\",\"fields\":[{\"name\":\"oldName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"newName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RenameDirCommand> ENCODER =
      new BinaryMessageEncoder<RenameDirCommand>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RenameDirCommand> DECODER =
      new BinaryMessageDecoder<RenameDirCommand>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RenameDirCommand> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RenameDirCommand> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RenameDirCommand>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RenameDirCommand to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RenameDirCommand from a ByteBuffer. */
  public static RenameDirCommand fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.String oldName;
  @Deprecated public java.lang.String newName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RenameDirCommand() {}

  /**
   * All-args constructor.
   * @param oldName The new value for oldName
   * @param newName The new value for newName
   */
  public RenameDirCommand(java.lang.String oldName, java.lang.String newName) {
    this.oldName = oldName;
    this.newName = newName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return oldName;
    case 1: return newName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: oldName = (java.lang.String)value$; break;
    case 1: newName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'oldName' field.
   * @return The value of the 'oldName' field.
   */
  public java.lang.String getOldName() {
    return oldName;
  }

  /**
   * Sets the value of the 'oldName' field.
   * @param value the value to set.
   */
  public void setOldName(java.lang.String value) {
    this.oldName = value;
  }

  /**
   * Gets the value of the 'newName' field.
   * @return The value of the 'newName' field.
   */
  public java.lang.String getNewName() {
    return newName;
  }

  /**
   * Sets the value of the 'newName' field.
   * @param value the value to set.
   */
  public void setNewName(java.lang.String value) {
    this.newName = value;
  }

  /**
   * Creates a new RenameDirCommand RecordBuilder.
   * @return A new RenameDirCommand RecordBuilder
   */
  public static avro.commands.RenameDirCommand.Builder newBuilder() {
    return new avro.commands.RenameDirCommand.Builder();
  }

  /**
   * Creates a new RenameDirCommand RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RenameDirCommand RecordBuilder
   */
  public static avro.commands.RenameDirCommand.Builder newBuilder(avro.commands.RenameDirCommand.Builder other) {
    return new avro.commands.RenameDirCommand.Builder(other);
  }

  /**
   * Creates a new RenameDirCommand RecordBuilder by copying an existing RenameDirCommand instance.
   * @param other The existing instance to copy.
   * @return A new RenameDirCommand RecordBuilder
   */
  public static avro.commands.RenameDirCommand.Builder newBuilder(avro.commands.RenameDirCommand other) {
    return new avro.commands.RenameDirCommand.Builder(other);
  }

  /**
   * RecordBuilder for RenameDirCommand instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RenameDirCommand>
    implements org.apache.avro.data.RecordBuilder<RenameDirCommand> {

    private java.lang.String oldName;
    private java.lang.String newName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(avro.commands.RenameDirCommand.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.oldName)) {
        this.oldName = data().deepCopy(fields()[0].schema(), other.oldName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.newName)) {
        this.newName = data().deepCopy(fields()[1].schema(), other.newName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RenameDirCommand instance
     * @param other The existing instance to copy.
     */
    private Builder(avro.commands.RenameDirCommand other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.oldName)) {
        this.oldName = data().deepCopy(fields()[0].schema(), other.oldName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.newName)) {
        this.newName = data().deepCopy(fields()[1].schema(), other.newName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'oldName' field.
      * @return The value.
      */
    public java.lang.String getOldName() {
      return oldName;
    }

    /**
      * Sets the value of the 'oldName' field.
      * @param value The value of 'oldName'.
      * @return This builder.
      */
    public avro.commands.RenameDirCommand.Builder setOldName(java.lang.String value) {
      validate(fields()[0], value);
      this.oldName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'oldName' field has been set.
      * @return True if the 'oldName' field has been set, false otherwise.
      */
    public boolean hasOldName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'oldName' field.
      * @return This builder.
      */
    public avro.commands.RenameDirCommand.Builder clearOldName() {
      oldName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'newName' field.
      * @return The value.
      */
    public java.lang.String getNewName() {
      return newName;
    }

    /**
      * Sets the value of the 'newName' field.
      * @param value The value of 'newName'.
      * @return This builder.
      */
    public avro.commands.RenameDirCommand.Builder setNewName(java.lang.String value) {
      validate(fields()[1], value);
      this.newName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'newName' field has been set.
      * @return True if the 'newName' field has been set, false otherwise.
      */
    public boolean hasNewName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'newName' field.
      * @return This builder.
      */
    public avro.commands.RenameDirCommand.Builder clearNewName() {
      newName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RenameDirCommand build() {
      try {
        RenameDirCommand record = new RenameDirCommand();
        record.oldName = fieldSetFlags()[0] ? this.oldName : (java.lang.String) defaultValue(fields()[0]);
        record.newName = fieldSetFlags()[1] ? this.newName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RenameDirCommand>
    WRITER$ = (org.apache.avro.io.DatumWriter<RenameDirCommand>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RenameDirCommand>
    READER$ = (org.apache.avro.io.DatumReader<RenameDirCommand>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
