/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mq.avro;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Commands {
  CreateFileCommand, RemoveFileCommand, UpdateFileCommand, MakeDirCommand, RemoveDirCommand, RenameDirCommand  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Commands\",\"namespace\":\"mq.avro\",\"symbols\":[\"CreateFileCommand\",\"RemoveFileCommand\",\"UpdateFileCommand\",\"MakeDirCommand\",\"RemoveDirCommand\",\"RenameDirCommand\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
