/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mq.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MessageEnvelope extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8540918826114348282L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MessageEnvelope\",\"namespace\":\"mq.avro\",\"fields\":[{\"name\":\"InnerSchema\",\"type\":{\"type\":\"enum\",\"name\":\"Commands\",\"symbols\":[\"CreateFileCommand\",\"RemoveFileCommand\",\"UpdateFileCommand\",\"MakeDirCommand\",\"RemoveDirCommand\",\"RenameDirCommand\"]}},{\"name\":\"payload\",\"type\":\"bytes\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MessageEnvelope> ENCODER =
      new BinaryMessageEncoder<MessageEnvelope>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MessageEnvelope> DECODER =
      new BinaryMessageDecoder<MessageEnvelope>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<MessageEnvelope> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<MessageEnvelope> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MessageEnvelope>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this MessageEnvelope to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a MessageEnvelope from a ByteBuffer. */
  public static MessageEnvelope fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public mq.avro.Commands InnerSchema;
  @Deprecated public java.nio.ByteBuffer payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MessageEnvelope() {}

  /**
   * All-args constructor.
   * @param InnerSchema The new value for InnerSchema
   * @param payload The new value for payload
   */
  public MessageEnvelope(mq.avro.Commands InnerSchema, java.nio.ByteBuffer payload) {
    this.InnerSchema = InnerSchema;
    this.payload = payload;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return InnerSchema;
    case 1: return payload;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: InnerSchema = (mq.avro.Commands)value$; break;
    case 1: payload = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'InnerSchema' field.
   * @return The value of the 'InnerSchema' field.
   */
  public mq.avro.Commands getInnerSchema() {
    return InnerSchema;
  }

  /**
   * Sets the value of the 'InnerSchema' field.
   * @param value the value to set.
   */
  public void setInnerSchema(mq.avro.Commands value) {
    this.InnerSchema = value;
  }

  /**
   * Gets the value of the 'payload' field.
   * @return The value of the 'payload' field.
   */
  public java.nio.ByteBuffer getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * @param value the value to set.
   */
  public void setPayload(java.nio.ByteBuffer value) {
    this.payload = value;
  }

  /**
   * Creates a new MessageEnvelope RecordBuilder.
   * @return A new MessageEnvelope RecordBuilder
   */
  public static mq.avro.MessageEnvelope.Builder newBuilder() {
    return new mq.avro.MessageEnvelope.Builder();
  }

  /**
   * Creates a new MessageEnvelope RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MessageEnvelope RecordBuilder
   */
  public static mq.avro.MessageEnvelope.Builder newBuilder(mq.avro.MessageEnvelope.Builder other) {
    return new mq.avro.MessageEnvelope.Builder(other);
  }

  /**
   * Creates a new MessageEnvelope RecordBuilder by copying an existing MessageEnvelope instance.
   * @param other The existing instance to copy.
   * @return A new MessageEnvelope RecordBuilder
   */
  public static mq.avro.MessageEnvelope.Builder newBuilder(mq.avro.MessageEnvelope other) {
    return new mq.avro.MessageEnvelope.Builder(other);
  }

  /**
   * RecordBuilder for MessageEnvelope instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MessageEnvelope>
    implements org.apache.avro.data.RecordBuilder<MessageEnvelope> {

    private mq.avro.Commands InnerSchema;
    private java.nio.ByteBuffer payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mq.avro.MessageEnvelope.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.InnerSchema)) {
        this.InnerSchema = data().deepCopy(fields()[0].schema(), other.InnerSchema);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MessageEnvelope instance
     * @param other The existing instance to copy.
     */
    private Builder(mq.avro.MessageEnvelope other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.InnerSchema)) {
        this.InnerSchema = data().deepCopy(fields()[0].schema(), other.InnerSchema);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.payload)) {
        this.payload = data().deepCopy(fields()[1].schema(), other.payload);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'InnerSchema' field.
      * @return The value.
      */
    public mq.avro.Commands getInnerSchema() {
      return InnerSchema;
    }

    /**
      * Sets the value of the 'InnerSchema' field.
      * @param value The value of 'InnerSchema'.
      * @return This builder.
      */
    public mq.avro.MessageEnvelope.Builder setInnerSchema(mq.avro.Commands value) {
      validate(fields()[0], value);
      this.InnerSchema = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'InnerSchema' field has been set.
      * @return True if the 'InnerSchema' field has been set, false otherwise.
      */
    public boolean hasInnerSchema() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'InnerSchema' field.
      * @return This builder.
      */
    public mq.avro.MessageEnvelope.Builder clearInnerSchema() {
      InnerSchema = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'payload' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getPayload() {
      return payload;
    }

    /**
      * Sets the value of the 'payload' field.
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public mq.avro.MessageEnvelope.Builder setPayload(java.nio.ByteBuffer value) {
      validate(fields()[1], value);
      this.payload = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'payload' field.
      * @return This builder.
      */
    public mq.avro.MessageEnvelope.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MessageEnvelope build() {
      try {
        MessageEnvelope record = new MessageEnvelope();
        record.InnerSchema = fieldSetFlags()[0] ? this.InnerSchema : (mq.avro.Commands) defaultValue(fields()[0]);
        record.payload = fieldSetFlags()[1] ? this.payload : (java.nio.ByteBuffer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MessageEnvelope>
    WRITER$ = (org.apache.avro.io.DatumWriter<MessageEnvelope>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MessageEnvelope>
    READER$ = (org.apache.avro.io.DatumReader<MessageEnvelope>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
